services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # Port HTTP pour abdou.com
      - "8080:8080"   # Dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web-network

  mon-app-dockerhub:
    image: salam630/jpetstore-groupe-app:latest
    container_name: mon-application
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jpetstore.rule=Host(`abdou.com`)"
      - "traefik.http.services.jpetstore.loadbalancer.server.port=8080"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge