version: '3'
services:
  # Le serveur SonarQube
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_server
    ports:
      - "9000:9000" # On pourra y accéder sur http://localhost:9000
    networks:
      - sonar_network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar

  # La base de données
  db:
    image: postgres:12
    container_name: postgres_db
    networks:
      - sonar_network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonar_network:

volumes:
  postgresql_data:
